version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  client:
    restart: always
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - mongo
